Errors on compile, simpler detect

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -13,7 +13,10 @@ function indent() {
 }
 
 if [ -z "$OVERLAY" ]; then
-  echo "'OVERLAY' environment variable not set, aborting..." | indent
+  echo "'OVERLAY' environment variable not set, aborting..."
+  exit 1
+elif [ ! -f $1/.buildpacks ] && [ ! -f $1/.buildpacks.$OVERLAY ]; then
+  echo "no .buildpacks neither .buildpacks.overlay-string file"
   exit 1
 fi
 
