Proper mods to fusing with overlay project

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
 
-if [ -f $1/.buildpacks ]; then
-  echo "Multipack"
-  exit 0
-else
-  echo "no .buildpacks file"
+if [ -z "$OVERLAY" ]; then
+  echo "'OVERLAY' environment variable not set, aborting..."
   exit 1
+elif [ ! -f $1/.buildpacks ] && [ ! -f $1/.buildpacks.$OVERLAY ] ; then
+  echo "no .buildpacks neither .buildpacks.overlay-string file"
+  exit 1
+else
+  echo "Heroku Overlay-Multi: a way to work with multiple apps and buildpacks in the same repository"
+  exit 0
 fi
+
